server:
  port: 8082

spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/final_backend
    username: sa
    password: sa
    
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie Service
